#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__


enum EVENT_TYPE { CL_BONEFIRE, CL_BONEOUT, CL_MATCH, CL_END_MATCH};
enum COMMAND {
	OP_RECV, OP_SEND, OP_ACCEPT, OP_NPC_MOVE, OP_NPC_ATTACK, OP_PLAYER_MOVE, OP_PLAYER_ATTACK, OP_PLAYER_RE, OP_PLAYER_HEAL, OP_PLAYER_DAMAGE
};
enum CL_STATE { ST_FREE, ST_ACCEPT, ST_INGAME }; //  접속 상태

enum STATE_Type { ST_SNOWMAN, ST_INBURN, ST_OUTBURN, ST_ANIMAL, ST_TORNADO}; //인게임 상태

enum COMBAT { COMBAT_DO, COMBAT_WIN, COMBAT_LOSE, COMBAT_RUN, COMBAT_END };

enum LEVEL { LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_END };
enum TYPE { TYPE_SWORD, TYPE_ARMOR, TYPE_END };
enum ITEM_STATE { STATE_EQUIP, STATE_UNEQUIP, STATE_END };

enum ITEM_Type{ ITEM_MAT, ITEM_UMB, ITEM_BAG, ITEM_SNOW, ITEM_JET, ITEM_ICE, ITEM_SPBOX};
enum OBJ_Type { PLAYER, ITEM_BOX, TONARDO, SUPPLYBOX};
enum Login_fail_Type {OVERLAP_ID, WORNG_ID, WORNG_PW, OVERLAP_AC, CREATE_AC};

enum BULLET_Type
{
	BULLET_SNOWBALL = 0,
	BULLET_ICEBALL,
	BULLET_SNOWBOMB
};



enum TELEPORT_Type
{
	TEL_FIRE = 1,
	TEL_BRIDGE,
	TEL_TOWER,
	TEL_ICE
};

enum CHEAT_Type
{
	CHEAT_HP_UP = 1,
	CHEAT_HP_DOWN,
	CHEAT_SNOW_PLUS,
	CHEAT_ICE_PLUS
};


#endif // !__ENUM_H__
